---
- name: Install kmod-tpe package
  tags: kmod-tpe
  yum: name=kmod-tpe
       enablerepo=elrepo,elrepo-testing
       state=present
  register: kmod_tpe_yum

- block:
    - name: Load tpe kernel module
      modprobe: name=tpe
                state=present
    - name: Configure tpe.conf
      template: src=tpe.conf.j2
                dest=/etc/sysctl.d/tpe.conf
                owner=root
                group=root
                mode=0644
      notify: reload sysctl
  tags: kmod-tpe
  when: kmod_tpe_yum|success
