---
- name: Ensure that the kmod-tpe package is installed
  tags: kmod-tpe
  become: true
  yum:
    enablerepo: elrepo
    name: kmod-tpe
    state: present
  register: kmod_tpe_yum

- name: Attempting to overlay kmod-tpe sysconfig configurations
  tags: kmod-tpe
  become: true
  template:
    src: "{{ item }}.j2"
    dest: "/etc/sysconfig/{{ item }}"
    owner: root
    group: root
    mode: 0644
  notify: execute tpe-setfattr-whitelist
  with_items:
    - tpe-exec-whitelist
    - tpe-lsmod-whitelist
    - tpe-mmap-whitelist
    - tpe-mprotect-whitelist
    - tpe-ptrace-whitelist
    - tpe-setuid-whitelist
    - tpe-uname-whitelist
  when: kmod_tpe_yum is success

- name: Attempting to overlay kmod-tpe sysctl.d configurations
  tags: kmod-tpe
  become: true
  template:
    src: tpe.conf.j2
    dest: /etc/sysctl.d/tpe.conf
    owner: root
    group: root
    mode: 0644
  when: kmod_tpe_yum is success

- name: Attempting to fetch kernel modules_disabled setting
  tags: kmod-tpe
  slurp:
    src: /proc/sys/kernel/modules_disabled
  register: kmod_tpe_slurp
  when: kmod_tpe_yum is success

- name: Attempting to manually load the tpe kernel module
  tags: kmod-tpe
  become: true
  modprobe:
    name: tpe
    state: present
  register: kmod_tpe_modprobe
  when:
    - kmod_tpe_slurp.content|b64decode|trim == '0'
    - kmod_tpe_yum is success

- name: Attempting to reload sysctl upon module loading success
  tags: kmod-tpe
  become: true
  command: |
    sysctl -p /etc/sysctl.d/tpe.conf
  when:
    - kmod_tpe_modprobe is not skipped
    - kmod_tpe_modprobe is not failed
...
